# Generated by Django 3.1.3 on 2021-04-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='created_at',
        ),
    ]
