# Generated by Django 3.1.3 on 2021-04-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Test',
        ),
    ]
